import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CssBaseline, CssVarsProvider } from "@mui/joy";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <CssVarsProvider>
                {/* must be used under CssVarsProvider */}
                <CssBaseline/>
    
                {/* The rest of your application */}
            </CssVarsProvider>
            {children}
        </body>
        </html>
    )
}
