import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CssBaseline, CssVarsProvider, Sheet } from "@mui/joy";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <CssVarsProvider>
                <CssBaseline/>
                <Sheet variant="outlined"
                       sx={{
                           width: 'auto',
                           mx: 2, // margin left & right
                           my: 2, // margin top & bottom
                           py: 2, // padding top & bottom
                           px: 2, // padding left & right
                           display: 'flex',
                           flexDirection: 'column',
                           gap: 2,
                           borderRadius: 'sm',
                           boxShadow: 'md',
                       }}>
                    {children}
                </Sheet>
            </CssVarsProvider>
        </body>
        </html>
    )
}
