### Get with default from/to date
GET {{host}}/api/parking/Accu?code={{DefaultKey}}
Content-Type: application/json

###

GET {{host}}/api/parking/P%20West?code={{DefaultKey}}
Content-Type: application/json

### Get with custom from date
GET {{host}}/api/parking/Accu?from=2023-10-03&code={{DefaultKey}}
Content-Type: application/json

### Get with custom from and to date
GET {{host}}/api/parking/P%20West?from=2023-10-01&to=2023-10-03&code={{DefaultKey}}
Content-Type: application/json
